### ISSUE TITLE
Even the native Promise cannot pass the promises-es6-tests

### ISSUE THREAD

**Issue by ysmood** [hax/my-promise#1]
I tested it with the native Promise of Node v5.0. It's hard to believe that even the native promise doesn't work well.

Maybe the `promises-es6-tests` itself is still using some outdated specs. The last git commit of it is a year ago. So I think it doesn't suit the job of measuring a implementation's correctness?

**Comment by hax** [comment]
I will recheck the current spec if I have time, but I don't think `promise-es6-tests` is outdated. Current Promise implementations in the browsers are known not full compliance, for example, subclassing of Promise, and some edge case: https://github.com/hax/test-promises/blob/master/promises-spec.md
